version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.03
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Run test
          command: |
            bash $(circleci tests glob "src/*.sh" | circleci tests split --split-by=timings)

workflows:
  test-workflow:
    jobs:
      - test